name: Clone and build Blocks

on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches: 
      - main
      - develop
    paths:
      - '**'  # Adjust this if you want to limit which files trigger the workflow
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: MyScratchBlocks/scratch-gui

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Build
        run: |
          npm install
          npm run build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Push To Codeberg
        run: |
          git config user.email "kRxZy_kRxZy@noreply.codeberg.org"
          git config user.name "SnapLabs[BOT]"
          git remote remove origin 
          git remote add origin https://KRXZY_KRXZY:5a14a111a6bec05904942fe16e7653e8b30a2781@codeberg.org/snaplabs/idk
          git fetch --unshallow
          git add build
          git commit -m "build editor"
          git push --set-upstream origin develop
